#variables:
#  DOCKER_DRIVER: overlay
 
stages:
  - spawn
  - build
  - test
  - release
  - deploy
  - cleanup
   
spawn_containers:
  stage: spawn
  before_script:
    - apk add docker-compose
    - docker-compose --version
  #  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo "Start docker-containers for compile sources"
  #  - set -o allexport; . ./docker/.env.staging.lc
    - docker-compose -f /src/docker-compose.yml up -d  
 
compile:
  stage: build
  script:
    - echo "Compile sources"
 
testing:
  stage: test
  script:
    - echo "Testing"
 
release-image:
  stage: release
  script:
    - echo "Build docker-image with sources"
 
deploy-to-review:
  stage: deploy
  script:
    - echo "Deploy docker-image with sources to rewiew"
 
deploy-to-prod:
  stage: deploy
  script:
    - echo "Deploy docker-image with sources to production"
  when: manual
 
cleanup:
  stage: cleanup
  when: always
  script:
    - echo "Stop & remove containers"