global:
  slack_api_url: 'https://hooks.slack.com/services/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'
  
route:
  receiver: 'slack-notifications'
  
receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#docker-test'