version: '3.3'
services:
  post_db:
    image: mongo:latest
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    #build: ./ui
    image: ${USERNAME}/ui
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
  post:
    #build: ./post-py
    image: ${USERNAME}/post
    networks:
      - back_net
      - front_net
  
  comment:
    #build: ./comment
    image: ${USERNAME}/comment
    networks:
      - back_net
      - front_net
    
volumes:
  post_db:

networks:
  front_net:
  back_net: